@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 26 21:11:48 +0530 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim cube_root_tb_behav -key {Behavioral:sim_1:Functional:cube_root_tb} -tclbatch cube_root_tb.tcl -view E:/STUDY/Books/Electronica/microcontrollers/BITS/sem 1/Reconfigurable computing/Assignments/Assignment 2/Cube_Root/cube_root_tb_behav.wcfg -log simulate.log"
call xsim  cube_root_tb_behav -key {Behavioral:sim_1:Functional:cube_root_tb} -tclbatch cube_root_tb.tcl -view E:/STUDY/Books/Electronica/microcontrollers/BITS/sem 1/Reconfigurable computing/Assignments/Assignment 2/Cube_Root/cube_root_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
